<div class="container-fluid">
    <div class="row-fluid">

        <div class="span3">
            <h2>Neuer Artikel</h2>
            <p>Einen neuen Artikel verfassen, planen oder direkt veröffentlichen.</p>
            <a class="btn btn-primary" href="<?=$this->baseUrl();?>/articles/add">Artikel anlegen »</a>
        </div>

        <div class="span3">
            <h2>Neue Kategorie</h2>
            <p>Eine neue Kategorie anlegen.</p>
            <a class="btn btn-primary" href="<?=$this->baseUrl();?>/categories/add">Kategorie anlegen »</a>
        </div>

        <div class="span3">
            <h2>Neues Thema</h2>
            <p>Ein neues Thema anlegen.</p>
            <a class="btn btn-primary" href="<?=$this->baseUrl();?>/topics/add">Thema anlegen »</a>
        </div>

        <div class="span3">
            <h2>Neues Bild</h2>
            <p>Ein neues Bild in den Bildpool legen und verschlagworten.</p>
            <a class="btn btn-primary" href="<?=$this->baseUrl();?>/assets/add">Bild hochladen »</a>
        </div>
    </div>
</div>