<div class="container-fluid">
    <?php
    if(count(CD_Message_Center::getInstance()->getMessages()) > 0) {
        echo CD_Message_Center::getInstance()->flush();
    }
    ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="well well-small">
                <a class="btn btn-primary" href="<?=$this->baseUrl();?>/<?=Zend_Controller_Front::getInstance()->getRequest()->getControllerName()?>/add">Add Item »</a>
            </div>
            <table class="table table-striped table-condensed table-hover">
                <thead>
                    <tr>
                        <th class="tiny">
                            #
                        </th>
                        <th class="main">
                            Name
                        </th>
                        <th class="tiny">
                            Actions
                        </th>
                    </tr>
                </thead>
                <?php
                    if(count($this->items) > 0) {
                        ?>
                        <tbody>
                            <?php
                                /** @var $item Application_Model_Article */
                                foreach($this->items as $item) {
                                    ?>
                                        <tr>
                                            <td>
                                                <?=$item->id?>
                                            </td>
                                            <td>
                                                <a href="<?=$this->baseUrl();?>/<?=Zend_Controller_Front::getInstance()->getRequest()->getControllerName()?>/view/id/<?=$item->id?>"><?=$item?></a>
                                            </td>
                                            <td>
                                                <a href="<?=$this->baseUrl();?>/<?=Zend_Controller_Front::getInstance()->getRequest()->getControllerName()?>/view/id/<?=$item->id?>"><i class="icon-eye-open"></i></a>
                                                <a href="<?=$this->baseUrl();?>/<?=Zend_Controller_Front::getInstance()->getRequest()->getControllerName()?>/deactivate/id/<?=$item->id?>"><i class="icon-remove"></i></a>
                                            </td>
                                        </tr>
                                    <?php
                                }
                            ?>
                        </tbody>
                        <?php
                    }
                ?>
            </table>

        </div>
    </div>
</div>