<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <?php
                if(count(CD_Message_Center::getInstance()->getMessages()) > 0) {
                    echo CD_Message_Center::getInstance()->flush();
                }
            ?>

            <h2>[<?=$this->item->getType()?> #<?=$this->item->id?>] <?=$this->item?></h2>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span9">
            <div class="well well-small">
                <?=$this->item->getDescriptionParsed()?>
            </div>
        </div>

        <div class="span3">
            <ul class="ticketinfo">
                <li>
                    <dl>
                        <dt>Project:</dt>
                        <dd><?=$this->item->getProject()?></dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>Type:</dt>
                        <dd>
                            <?=$this->item->getType()?>
                        </dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>Author:</dt>
                        <dd><?=$this->item->getAuthor()?></dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>Attached to:</dt>
                        <dd>
                            <?=$this->item->getAttachedTo()?>
                            <a href="#" data-toggle="dropdown"><i class="icon-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <?php
                                foreach($this->users as $user) {
                                    ?><li><a href="<?=$this->baseUrl();?>/tickets/assign/id/<?=$this->item->id?>/userId/<?=$user->id?>"><?=$user?></a></li><?php
                                }
                                ?>
                                <li class="divider"></li>
                                <li><a href="#">Mir zuweisen</a></li>
                            </ul>
                        </dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>State:</dt>
                        <dd><?=$this->item->getState()?>
                            <a href="#" data-toggle="dropdown"><i class="icon-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <?php
                                    foreach($this->states as $state) {
                                        ?><li><a href="<?=$this->baseUrl();?>/tickets/setState/id/<?=$this->item->id?>/stateId/<?=$state->id?>"><?=$state?></a></li><?php
                                    }
                                ?>
                            </ul>
                        </dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>Created:</dt>
                        <dd><?=date('d.m.Y, H:i:s', $this->item->getCreatedAsTimestamp())?></dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>Last Updt.:</dt>
                        <dd><?=date('d.m.Y, H:i:s', $this->item->getUpdatedAsTimestamp())?></dd>
                    </dl>
                </li>
            </ul>

            <a class="btn btn-primary pull-right" href="<?=$this->baseUrl();?>/updates/add/for/<?=$this->item->id?>">Update »</a>
        </div>
    </div>


    <?php
        if($this->item->id AND count($this->item->getUpdates()) > 0) {
            foreach($this->item->getUpdates() as $update) {
                ?>
                <hr>
                <div class="row-fluid">
                    <div class="span9">
                        <?php if(trim($update->getDescriptionParsed()) != '') {
                        ?>
                        <div class="well well-small">
                            <?=$update->getDescriptionParsed()?>
                        </div>
                        <?php
                        } ?>
                    </div>

                    <div class="span3">
                        <ul class="ticketinfo">
                            <li>
                                <dl>
                                    <dt>Autor:</dt>
                                    <dd>Cem Derin</dd>
                                </dl>
                            </li>
                            <li>
                                <dl>
                                    <dt>Update:</dt>
                                    <dd><?=date('d.m.Y, H:i:s', $update->getUpdatedAsTimestamp())?></dd>
                                </dl>
                            </li>

                            <?php if($update->getState()->id){ ?>
                            <li class="highlight">
                                <dl>
                                    <dt>State:</dt>
                                    <dd><?=$update->getState()?></dd>
                                </dl>
                            </li>
                            <?php } ?>

                            <?php if($update->getAttachedTo()->id) { ?>
                            <li class="highlight">
                                <dl>
                                    <dt>Attached to:</dt>
                                    <dd><?=$update->getAttachedTo()?></dd>
                                </dl>
                            </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
                <?php
            }
        }
    ?>




    <hr>
    <div class="row-fluid">
        <div class="span12">
            <a class="btn btn-primary pull-right" href="<?=$this->baseUrl();?>/updates/add/for/<?=$this->item->id?>">Update »</a>
        </div>
    </div>
</div>
