<!DOCTYPE html>
<html>
<head>
    <title>nomobu install</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="<?=$this->baseUrl()?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=$this->baseUrl()?>/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?=$this->baseUrl()?>/css/nomobu.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="<?=$this->baseUrl()?>/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body class="install"><div class="container-fluid">
    <?php echo $this->layout()->content ?>
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/jquery.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/js/bootstrap.min.js"></script>
</body>
</html>