<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <h1>nomobu installer</h1>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12 well well-small clearfix">

            <p class="header">
                Nomobu is now ready to use. The installer has changed your config-file. Make sure to include this one
                in your backups. You will find it at <code>./application/configs/config.ini</code>
            </p>
            <a href="<?=$this->baseUrl()?>" class="btn btn-primary pull-right">Start using nomobu »</a>
        </div>
    </div>
</div>